fix: switch to skopeo to avoid REST rate limits

diff --git a/.github/workflows/base-glibc-debian-bash.yaml b/.github/workflows/base-glibc-debian-bash.yaml
--- a/.github/workflows/base-glibc-debian-bash.yaml
+++ b/.github/workflows/base-glibc-debian-bash.yaml
@@ -140,25 +140,16 @@ jobs:
 
     - name: Check Tags
       run: |
-        # FIX upstream: Quay.io does not support immutable images currently.
-        #               => Try to use the REST API to check for duplicate tags.
-        response="$(
-          curl -sL \
-            'https://quay.io/api/v1/repository/bioconda/${{ steps.build.outputs.image }}/tag/'
-          )"
-
+        # Quay.io does not support immutable images.
+        # => Check for duplicate tags to avoid overwriting existing images.
         existing_tags="$(
-          printf %s "${response}" \
-            | jq -r '.tags[]|select(.end_ts == null or .end_ts >= now)|.name'
-          )" \
-          || {
-            printf %s\\n \
-              'Could not get list of image tags.' \
-              'Does the repository exist on Quay.io?' \
-              'Quay.io REST API response was:' \
-              "${response}"
-            exit 1
-          }
+          skopeo list-tags docker://quay.io/bioconda/${{ steps.build.outputs.image }} \
+            | jq -r '.Tags[]'
+        )" \
+        || {
+          echo 'Could not list tags via skopeo.'
+          exit 1
+        }
         for tag in ${{ steps.build.outputs.tags }} ; do
           case "${tag}" in
             latest | '${{ env.MAJOR_VERSION }}' ) ;;
diff --git a/.github/workflows/bot.yaml b/.github/workflows/bot.yaml
--- a/.github/workflows/bot.yaml
+++ b/.github/workflows/bot.yaml
@@ -89,25 +89,16 @@ jobs:
 
     - name: Check Tags
       run: |
-        # FIX upstream: Quay.io does not support immutable images currently.
-        #               => Try to use the REST API to check for duplicate tags.
-        respone="$(
-          curl -sL \
-            'https://quay.io/api/v1/repository/bioconda/${{ steps.buildah-build.outputs.image }}/tag/'
-          )"
-
+        # Quay.io does not support immutable images.
+        # => Check for duplicate tags to avoid overwriting existing images.
         existing_tags="$(
-          printf %s "${respone}" \
-            | jq -r '.tags[]|select(.end_ts == null or .end_ts >= now)|.name'
-          )" \
-          || {
-            printf %s\\n \
-              'Could not get list of image tags.' \
-              'Does the repository exist on Quay.io?' \
-              'Quay.io REST API response was:' \
-              "${respone}"
-            exit 1
-          }
+          skopeo list-tags docker://quay.io/bioconda/${{ steps.buildah-build.outputs.image }} \
+            | jq -r '.Tags[]'
+        )" \
+        || {
+          echo 'Could not list tags via skopeo.'
+          exit 1
+        }
         for tag in ${{ steps.buildah-build.outputs.tags }} ; do
           if [ \! "${tag}" = '${{ matrix.tag }}' ] ; then
             if printf %s "${existing_tags}" | grep -qxF "${tag}" ; then
